# Generated by Django 4.2.4 on 2023-08-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
